version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ${PWD}/srcs/requirements/mariadb
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_ROOT_PASS=${DB_ROOT_PASS}
    restart : always
    volumes:
      - DB:/var/lib/mysql/
    networks:
      - host

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ${PWD}/srcs/requirements/wordpress
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
    restart : always
    depends_on: 
      - mariadb
    volumes:
      - DB-WP:/var/www/html/wordpress
    networks:
      - host

  nginx:
    image: nginx
    container_name: nginx
    build: ${PWD}/srcs/requirements/nginx
    restart : always
    ports:
      - 443:443
    depends_on: 
      - wordpress
    volumes:
      - DB-WP:/var/www/html/wordpress
    networks:
      - host

      ############# bonus #############

  redis:
    image: redis
    container_name: redis
    build: ${PWD}/srcs/requirements/bonus/redis
    restart : always
    networks:
      - host
  
  static-site:
    image: static-site
    container_name: static-site
    build: ${PWD}/srcs/requirements/bonus/static-site
    restart : always
    networks:
      - host

  admidner:
    image: adminer
    container_name: adminer
    build: ${PWD}/srcs/requirements/bonus/adminer
    restart : always
    networks:
      - host

  portainer:
    image: portainer
    container_name: portainer
    build: ${PWD}/srcs/requirements/bonus/portainer
    restart : always
    networks:
      - host
    volumes:
      - DB-P:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9443:9443

volumes:
  DB-WP:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/srcs/data/db-wp
  DB:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/srcs/data/db
  DB-P:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/srcs/data/db-p

networks:
  host:
    driver: bridge
