version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    ports:
      - 3306:3306
    volumes:
      - DB:/var/lib/mysql
    networks:
      - host

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./wordpress
    ports:
      - 9000:9000
    volumes:
      - DB-WP:/var/www/html/wordpress
    networks:
      - host

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 443:443
    volumes:
      - DB-WP:/var/www/html/wordpress
    networks:
      - host

volumes:
  DB-WP:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/DB-WP/
  DB:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/DB/

networks:
  host:
    driver: bridge
