version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    ports:
      - 3306:3306
    # networks:
    #   - host

  wordpress:
    container_name: wordpress
    build: ./wordpress
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    volumes:
      - DB-WP:/var/www/html/wordpress
    # networks:
    #   - host

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - DB-WP:/var/www/html/wordpress
    # networks:
    #   - host

volumes:
  DB-WP:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/DB-WP/

# networks:
#   host:
#     driver: bridge
