FROM debian:buster

RUN apt update
RUN apt install wget -y 
RUN apt install php7.3 -y
RUN  apt install php-mysql -y

WORKDIR /var/www/html/adminer/

RUN wget http://www.adminer.org/latest.php -O index.php

RUN chmod 755 -R index.php
RUN chown -R www-data:www-data /var/www/html/adminer/


CMD ["php", "-S", "[::]:8080", "-t", "/var/www/html"]